 name: SayHello

 on:
   push:
     branches:
       - develop
       - main
       
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Get Your Code
         uses: actions/checkout@v2
          
       - name: Say Hello
         run: |
          if: ["$GITHUB_REF" == "refs/head/develop"]; then
               echo "say hello develop"
          elfi:["GITHUB_REF" == "refs/head/main"]; then
               echo "say hello main"
            fi   
